'use strict';

require('./account');
require('./auditlog');
require('./configimex');
require('./configitem');
require('./confignamespace');
require('./dashboard');
require('./dnsrecord');
require('./dnszone');
require('./domainhijacking');
require('./ebsvolume');
require('./ec2instance');
require('./emails');
require('./instanceage');
require('./logevent');
require('./login');
require('./logout');
require('./requiredtag');
require('./role');
require('./search');
require('./s3');
require('./template');
require('./user');
require('./volumeaudit');
require('./vpc');
require('./elb');
