/*
 * AWSAPICallViaCloudTrail
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package s3
// RetentionInfo struct for RetentionInfo
type RetentionInfo struct {
	LastModifiedTime int64 `json:"lastModifiedTime,omitempty"`
	RetainUntilTime int64 `json:"retainUntilTime,omitempty"`
	RetainUntilMode string `json:"retainUntilMode,omitempty"`
}
