/*
 * AWSAPICallViaCloudTrail
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package s3
// UserIdentity struct for UserIdentity
type UserIdentity struct {
	SessionContext SessionContext `json:"sessionContext"`
	AccessKeyId string `json:"accessKeyId"`
	AccountId string `json:"accountId"`
	PrincipalId string `json:"principalId"`
	Type string `json:"type"`
	Arn string `json:"arn"`
}
