/*
 * AWSAPICallViaCloudTrail
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package s3
// RequestParameters struct for RequestParameters
type RequestParameters struct {
	BucketName string `json:"bucketName"`
	LegalHold string `json:"legal-hold,omitempty"`
	Key string `json:"key"`
	Retention string `json:"retention,omitempty"`
}
