/*
 * AWSAPICallViaCloudTrail
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package s3
// AdditionalEventData struct for AdditionalEventData
type AdditionalEventData struct {
	ObjectRetentionInfo ObjectRetentionInfo `json:"objectRetentionInfo,omitempty"`
	XAmzId2 string `json:"x-amz-id-2"`
}
