/*
 * AWSAPICallViaCloudTrail
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package s3
import (
	"time"
)
// Attributes struct for Attributes
type Attributes struct {
	MfaAuthenticated string `json:"mfaAuthenticated"`
	CreationDate time.Time `json:"creationDate"`
}
