/*
 * AWSAPICallViaCloudTrail
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package s3
// ObjectRetentionInfo struct for ObjectRetentionInfo
type ObjectRetentionInfo struct {
	LegalHoldInfo LegalHoldInfo `json:"legalHoldInfo,omitempty"`
	RetentionInfo RetentionInfo `json:"retentionInfo,omitempty"`
}
