/*
 * AWSAPICallViaCloudTrail
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package s3
import (
	"time"
)
// AwsapiCallViaCloudTrail struct for AwsapiCallViaCloudTrail
type AwsapiCallViaCloudTrail struct {
	RequestParameters RequestParameters `json:"requestParameters"`
	UserIdentity UserIdentity `json:"userIdentity"`
	AdditionalEventData AdditionalEventData `json:"additionalEventData"`
	EventID string `json:"eventID"`
	AwsRegion string `json:"awsRegion"`
	EventVersion string `json:"eventVersion"`
	ResponseElements *map[string]interface{} `json:"responseElements"`
	SourceIPAddress string `json:"sourceIPAddress"`
	EventSource string `json:"eventSource"`
	ErrorMessage string `json:"errorMessage,omitempty"`
	Resources []map[string]interface{} `json:"resources"`
	ErrorCode string `json:"errorCode,omitempty"`
	UserAgent string `json:"userAgent"`
	ReadOnly bool `json:"readOnly"`
	EventType string `json:"eventType"`
	VpcEndpointId string `json:"vpcEndpointId"`
	RequestID string `json:"requestID"`
	EventTime time.Time `json:"eventTime"`
	EventName string `json:"eventName"`
	RecipientAccountId string `json:"recipientAccountId"`
}
