/*
 * RDSDBInstanceEvent
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package CinqOpenAPIAWSRDS
import (
	"time"
)
// RdsdbInstanceEvent struct for RdsdbInstanceEvent
type RdsdbInstanceEvent struct {
	SourceArn string `json:"SourceArn"`
	Message string `json:"Message"`
	SourceType string `json:"SourceType"`
	SourceIdentifier string `json:"SourceIdentifier"`
	EventCategories []string `json:"EventCategories"`
	Date time.Time `json:"Date"`
}
