/*
 * RDSDBInstanceEvent
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package CinqOpenAPIAWSRDS
import (
	"time"
)
// AwsEvent struct for AwsEvent
type AwsEvent struct {
	Detail RdsdbInstanceEvent `json:"detail"`
	DetailType string `json:"detail-type"`
	Resources []string `json:"resources"`
	Id string `json:"id"`
	Source string `json:"source"`
	Time time.Time `json:"time"`
	Region string `json:"region"`
	Version string `json:"version"`
	Account string `json:"account"`
}
